#!/usr/bin/env python3
from http.server import HTTPServer, SimpleHTTPRequestHandler, test
import sys


# get names of all files from current directory
# creates a file called filelist.json and writes all the file names to it
import os
import json
img_dir = "./jpg"
filelist = os.listdir(img_dir)
filelist_name = 'file_list.json'


files = []
for listitem in filelist:
	print(listitem)
	if listitem != os.path.basename(__file__) and listitem != filelist_name:
		if listitem.split('.')[-1] in ['png', 'jpg']:
			files.append(listitem)

with open(filelist_name, 'w') as filehandle:
	json.dump(files, filehandle)


class CORSRequestHandler (SimpleHTTPRequestHandler):
    def end_headers (self):
        self.send_header('Access-Control-Allow-Origin', '*')
        SimpleHTTPRequestHandler.end_headers(self)

if __name__ == '__main__':
    test(CORSRequestHandler, HTTPServer, port=int(sys.argv[1]) if len(sys.argv) > 1 else 8080)

