shape(4)
.scale(0.2,9)
.modulate(osc(20,.1))
.repeat(4,4)
.scrollY(() => -1*(time/5 - Math.sin(time/10)))
.scrollX(() => -1*(time/5 + Math.sin(time/10)))
.rotate(0.6)
.invert()
// .kaleid(1.4)
.rotate(() => (time))
.out()
